name: ci
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: pnpm/action-setup@v2
              with:
                  version: 6.0.2
            - name: Install modules
              run: pnpm install
            - name: Run ESLint
              run: eslint src/**/*.ts
