name: ci
on:
    push:
    pull_request:
jobs:
    svelte-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v2
              with:
                  version: latest
            - name: Install modules
              run: pnpm install
            - name: Run Svelte-Check
              run: pnpm run svelte
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v2
              with:
                  version: latest
            - name: Install modules
              run: pnpm install
            - name: Run ESLint
              run: pnpm run lint
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v2
              with:
                  version: latest
            - name: Install modules
              run: pnpm install
            - name: Run Prettier
              run: pnpm run format
    compile:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v2
              with:
                  version: latest
            - name: Install modules
              run: pnpm install
            - name: Run tsc
              run: tsc --noEmit
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v2
              with:
                  version: latest
            - name: Install modules
              run: pnpm install
            - name: Run build
              run: pnpm run build
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v2
              with:
                  version: latest
            - name: Install modules
              run: pnpm install
            - name: Run tests
              run: pnpm test
