name: test
on:
    push:
    pull_request:
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: pnpm/action-setup@v2
              with:
                  version: 6.0.2
            - name: Install modules
              run: pnpm install
            - name: Run ESLint
              run: pnpm run lint
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: pnpm/action-setup@v2
              with:
                  version: 6.0.2
            - name: Install modules
              run: pnpm install
            - name: Run Prettier
              run: pnpm run format
    compile:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: pnpm/action-setup@v2
              with:
                  version: 6.0.2
            - name: Install modules
              run: pnpm install
            - name: Run tsc
              run: tsc --noEmit
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: pnpm/action-setup@v2
                with:
                    version: 6.0.2
            -   name: Install modules
                run: pnpm install
            -   name: Run build
                run: pnpm run build
